### PR TITLE
Issue: XCTRACK competition class is HSCCL

### PR DESCRIPTION
**Pull request by eltorio**
XCTRACK CCL header is like:
HSCCLCOMPETITION CLASS:FAI-3 (PG)
So just a small change to the regex can allow this header.
Thanks for your work.
Ronan

### CODE REVIEW

**Comment by Turbo87** [comment]
what does `S` mean? is this a new addition to the IGC file spec?

**Comment by eltorio** [comment]
> what does `S` mean? is this a new addition to the IGC file spec?

I don't know. I adapted your parser for the french Hike&Fly paragliding contest, a[nd some users complains about not parsable tracks](https://github.com/eltorio/CFDTrackJoiner/commit/8b7f9b35d7ee2c0b839b51de663315091584aec5). In fact all of them have «HSCCLCOMPETITION CLASS» in place of HFCCL… so I change the REGEX and for cosmetic also :
    IGCParser.prototype.parseCompetitionClass = function (line) {
       -  return this.parseTextHeader('GID', RE_CCL_HEADER, line);
       + return this.parseTextHeader('CCL', RE_CCL_HEADER, line);

Thanks for you library

**Comment by corstian** [comment]
As per section 3.3.2 at https://xp-soaring.github.io/igc_file_format/igc_format_2008.html;

> I think this is a TYPO: HSCID would not be valid format. The correct record should be HFCID. Same for HFCCL.

That may a possible source for the confusion.

**Comment by eltorio** [comment]
> As per section 3.3.2 at https://xp-soaring.github.io/igc_file_format/igc_format_2008.html;
> 
> > I think this is a TYPO: HSCID would not be valid format. The correct record should be HFCID. Same for HFCCL.
> 
> That may a possible source for the confusion.

Sure it seems to be a typo in the official specs but [XCTrack](https://play.google.com/store/apps/details?id=org.xcontest.XCTrack) has now 100000+ installations and it writes the header like the 3.3.2 sample section in the specs.
The question : if in official specs there is a typo, does this typo becomes a spec?
I think when a lot of device have this typo it becomes a new spec 🤣

So even it is a typo, a spec is a spec…

**Comment by Turbo87** [comment]
it is actually not a typo. the `S` in that example stands for "Data **S**ource" as described in the table above that format description, and the table clearly states which values are valid ("F, O or P")

**Pull request closed without merging**
